### ISSUE TITLE
 No publishable resources for tag [laravel-midtrans-config].

### ISSUE THREAD

**Issue by Mirmuxsin** [sawirricardo/laravel-midtrans#10]
php artisan vendor:publish --tag="laravel-midtrans-config"

   INFO  No publishable resources for tag [laravel-midtrans-config].

**Comment by rheznendra** [comment]
same problem here

**Comment by Mirmuxsin** [comment]
@sawirricardo pls take a look

**Comment by sawirricardo** [comment]
Hi, should be fixed, sorry for the long wait time 🙏🏻. Let me know if you still face this issue. Thanks!

**Comment by sawirricardo** [comment]
And it's also changed to `midtrans-config`
