### ISSUE TITLE
Cannot assign null to property Sawirricardo\Midtrans\Dto\TransactionDetails::$order_id of type string

### ISSUE THREAD

**Issue by Mirmuxsin** [sawirricardo/laravel-midtrans#12]
$details = new TransactionDetails();
        $details->order_id = 123123;
        $transaction = new TransactionDto();
        $transaction->transaction_details = $details;
        return Midtrans::new()->snap()->create($transaction)->redirect_url;

it returns "Cannot assign null to property Sawirricardo\Midtrans\Dto\TransactionDetails::$order_id of type string"

**Comment by sawirricardo** [comment]
the order id needs to be a string 👍

**Comment by Mirmuxsin** [comment]
I know that it is. Still showing the same error even I put there $details->order_id = '123123' or $details->order_id = uniqid();
